name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure your project dependencies are in this file
        pip install sphinx  # Add any additional Sphinx extensions or themes

    - name: Build documentation
      run: |
        cd docs
        make html  # This should be adjusted to match your build process (e.g., `make html` or `sphinx-build`)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/  # Ensure this matches the output directory